/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WhitelabelRouteImport } from './routes/whitelabel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitelabelRoute = WhitelabelRouteImport.update({
  id: '/whitelabel',
  path: '/whitelabel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/whitelabel': typeof WhitelabelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/whitelabel': typeof WhitelabelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/whitelabel': typeof WhitelabelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/delivery'
    | '/faq'
    | '/platform'
    | '/pricing'
    | '/whitelabel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/delivery'
    | '/faq'
    | '/platform'
    | '/pricing'
    | '/whitelabel'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/delivery'
    | '/faq'
    | '/platform'
    | '/pricing'
    | '/whitelabel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  WhitelabelRoute: typeof WhitelabelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitelabel': {
      id: '/whitelabel'
      path: '/whitelabel'
      fullPath: '/whitelabel'
      preLoaderRoute: typeof WhitelabelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  WhitelabelRoute: WhitelabelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
